version: '3'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
