apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app
          # image: hafidd34/front-end-vue:v1
          image: hafidd34/front-end-vue:v4
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: vue-service
spec:
  selector:
    app: vue-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
